# Generated by Django 3.1.3 on 2023-04-25 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='wenwu',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='wenwu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category', verbose_name='分类'),
        ),
    ]
